### PR TITLE
Make reproduction code work

### PR DESCRIPTION
**Pull request by sbfnk**
Fixes all errors and warnings when rendering `ExtendedMethods.Rmd` from a bare clone of this repo, making the analysis fully reproducible. Visual inspection suggests the results are indeed fully reproduced.

### CODE REVIEW

**Comment by sbfnk** [comment]
Fixes #5.

**Comment by terrycojones** [comment]
Hi Sebastian - thanks! This looks good to me, but I need to leave it to @gbiele to have a look (as you might have guessed, based on the `/Users/guidobiele` :-)).

I just realized that I have run into your name before, Christian Drosten mentioned you just before or after xmas.

Thanks again!

**Comment by gbiele** [comment]
Thanks for the effort Sebastian!
I'll look at this tomorrow.

**Review by gbiele — COMMENTED** [review]
I think this is, like some of the other submitted changes to the code, in order to avoid warning messages, and not because the NA lead downstream to errors.

**Review by gbiele — COMMENTED** [review]
I don't mind removing this. but the type argument may be needed on some platforms (if I remember correctly i added it when doing things on linux)

**Review by gbiele — COMMENTED** [review]
Thanks for catching this!
We did the actual analysis with a related set of scripts and always updated the R markdown and associated files accordingly, when the actual analysis scripts changed. 
Therefore not all code in this repo was always executed (this would have been to time-consuming), which made me overlook some needed updates.

**Review by gbiele — COMMENTED** [review]
Thanks for finiding the solution to this error!

**Comment by sbfnk** [comment]
Thanks for reviewing this - fyi as far as I can see your comments are not appearing in-line so it's not 100% clear what they're referring to but I can guess.

On your comments so far:

> I think this is, like some of the other submitted changes to the code, in order to avoid warning messages, and not because the NA lead downstream to errors.

Yes, sorry the PR contains a mixture of the two which is perhaps not ideal.

> I don't mind removing this. but the type argument may be needed on some platforms (if I remember correctly i added it when doing things on linux)

I ran on linux and got an error - the proposed changes are from my attempts to reverse engineer what may have been the intention (see changes to the `type`/`device` arguments further down).

**Review by gbiele — COMMENTED** [review]
is this the same as https://github.com/VirologyCharite/SARS-CoV-2-VL-paper/pull/9/commits/d9d23279f502fc482ef27d723669383a3cd5d410 ?

**Review by gbiele — COMMENTED** [review]
is this the same as https://github.com/VirologyCharite/SARS-CoV-2-VL-paper/pull/9/commits/811b6374334dee934d228dae448df0e69f90897f

**Review by gbiele — COMMENTED** [review]
As I wrote in another comment, this was added to deal with the linux system used for some analyses, but I don't mind removing this

**Review by gbiele — COMMENTED** [review]
I don't think this changes the plot, but I don't mind the change

**Comment by gbiele** [comment]
@sbfnk Sorry, I did not see that my comments are not linked to the relevant lines. I'm trying to figure this out now!

**Comment by gbiele** [comment]
> Fixes #5.

is this just a comment, or does this add files with posterior samples?

**Comment by gbiele** [comment]
> Fixes #5.
@sbfnk 
Thanks again for all the effort Sebastian!
I think we can merge this. My only question is if the comment above is just a summary of the effects of all the commits you made, or if this refers to the uploading of posterior samples we discusses here: https://github.com/VirologyCharite/SARS-CoV-2-VL-paper/issues/5. I don't mind also uploading the posterior samples, but I'm not sure if this amount of data would be covered by the plan under which this repo is hosted. What do you think, @terrycojones?

**Comment by sbfnk** [comment]
I didn’t add any posterior samples so I only added the comment so that issue gets closed. Arguably making the Rmd runnable removes the need for adding the samples (which could still be of benefit but a GitHub repo possibly not an appropriate platform for storage).

**Pull request merged**
